# Generated by Django 4.1.2 on 2022-10-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongtoShort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(max_length=500)),
                ('custom_name', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('vist_count', models.IntegerField(default=0)),
            ],
        ),
    ]
